# 配置文件用于定义各种服务的连接和认证信息，以确保应用程序能正确地与这些服务通信。
multirag:
  # multirag服务的监听地址
  host: 127.0.0.1
  # multirag服务的HTTP端口
  http_port: 8123
  # multirag服务的SECRET_KEY
  secret_key: 'multirag'

postgresql:
  # 数据库的类型
  name: 'postgresql'
  # 数据库的名称
  dbname: ''
  # postgresql数据库的用户名
  user: ''
  # postgresql数据库的密码
  password: ''
  # postgresql数据库的主机名
  host: '127.0.0.1'
  # postgresql数据库的端口
  port: 5432
  # postgresql的最大连接数
  max_connections: 100
  # postgresql的过期超时时间
  stale_timeout: 30

minio:
  # MinIO服务的用户名
  user: ''
  # MinIO服务的密码
  password: ''
  # MinIO服务的主机名和端口
  host: ''
  # MinIO服务的主机名和端口
  region: ''
  # 工作流过程中使用的桶名称
  workflow_bucket: 'multirag-workflow'

azure:
  auth_type: 'sas'
  container_url: 'container_url'
  sas_token: 'sas_token'
#azure:
#  auth_type: 'spn'
#  account_url: 'account_url'
#  client_id: 'client_id'
#  secret: 'secret'
#  tenant_id: 'tenant_id'
#  container_name: 'container_name'
s3:
  access_key: 'access_key'
  secret_key: 'secret_key'
  region: 'region'

milvus:
  # Milvus服务的主机地址
  hosts: 'http://127.0.0.1:19530'
  # Milvus服务的用户名
  username: 'root'
  # Milvus服务的密码
  password: 'Milvus'

es:
  # Elasticsearch服务的主机地址
  hosts: ''
  # Elasticsearch服务的用户名
  username: ''
  # Elasticsearch服务的密码
  password: ''

infinity:
  uri: 'infinity:23817'
  db_name: 'default_db'


redis:
  # Redis数据库的编号
  db: 1
  # Redis数据库的密码
  password: ''
  # Redis数据库的主机名和端口
  host: '127.0.0.1:6379'

user_default_llm:
  factory: 'ZHIPU-AI'
  api_key: '7ae32940233e38153d5ebaf94844f3e2.gwrz4P0tH9IDijUv'
  base_url: ''
  default_models:
    chat_model: 'glm-4-airx'
    embedding_model: 'BAAI/bge-large-zh-v1.5@BAAI'
    rerank_model: ''
    asr_model: ''
    image2text_model: ''

oauth:
  github:
    # GitHub OAuth的客户端ID
    client_id: xxxxxxxxxxxxxxxxxxxxxxxxx
    # GitHub OAuth的密钥
    secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    # GitHub OAuth的访问令牌URL
    url: https://github.com/login/oauth/access_token
  feishu:
    # 飞书OAuth的应用ID
    app_id: cli_xxxxxxxxxxxxxxxxxxx
    # 飞书OAuth的应用密钥
    app_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    # 飞书OAuth的应用访问令牌URL
    app_access_token_url: https://open.feishu.cn/open-apis/auth/v3/app_access_token/internal
    # 飞书OAuth的用户访问令牌URL
    user_access_token_url: https://open.feishu.cn/open-apis/authen/v1/oidc/access_token
    # 飞书OAuth的授权类型
    grant_type: 'authorization_code'

authentication:
  client:
    # 客户端认证开关
    switch: false
    # HTTP应用的密钥
    http_app_key:
    # HTTP应用的密钥
    http_secret_key:
  site:
    # 站点认证开关
    switch: false

permission:
  # 权限检查开关
  switch: false
  # 是否启用组件权限检查
  component: false
  # 是否启用数据集权限检查
  dataset: false

script_scheduler:
  # 如果源码部署，则使用localhost，如果docker部署，则使用宿主机的ip
  host: localhost
#  host: xxx.xxx.xxx.xxx
  port: 8124

